logo: https://avatars.githubusercontent.com/u/84224795?s=280&amp;v=4
image: https://avatars.githubusercontent.com/u/84224795?s=280&amp;v=4

github:
  private: false
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/fastrodev/fastro"

title: Fastro
description: Fast and simple web application framework for deno
google_analytics: UA-165990288-1