github:
  private: false
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/fastrodev/fastro"

title: Fastro

description: Fast and simple web application framework for deno

image:
  path: /assets/img/84224795.png
  height: 100
  width: 100
  alt: Twitter Logo

google_analytics: UA-165990288-1