github:
  private: false
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/fastrodev/fastro"

theme: jekyll-theme-primer

title: Fastro

description: Fast and simple web application framework for deno

image: /assets/img/84224795.png

google_analytics: UA-165990288-1

plugins:
  - jekyll-seo-tag