github:
  private: false
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/fastrodev/fastro"

theme: jekyll-theme-primer

title: Fastro

description: Fast and simple web application framework with native Deno Request and Response. You can use the built-in functions and objects that are already available according to your needs – such as all the Request properties, headers, cookies, and more.

twitter:
  username: fastrodev
  card: summary

image: "/assets/img/84224795.png"

google_analytics: UA-165990288-1

plugins:
  - jekyll-seo-tag