logo: https://avatars.githubusercontent.com/u/84224795?s=400&u=dd9afaa40b9a8ddd7e62307d836d20b091dae2e0&v=4

github:
  private: false
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/fastrodev/fastro"

title: Fastro
description: Fast and simple web application framework for deno
google_analytics: UA-165990288-1